### ISSUE TITLE
Query too complex error with out of the box setup

### ISSUE THREAD

**Issue by mschipperheyn** [vendure-ecommerce/vendure-demo#39]
Hi,

Ran into a Query too complex error with the out of the box setup. 

We need to add `maxQueryComplexity: 10000` to `HardenPlugin.init` in order for this demo server to work with any kind of query (using `RUN ["./install-storefront.sh", "v0.3.1"]`). I recommend adding that in order not to have developers run into an early wall.

**Comment by sadabnepal** [comment]
@michaelbromley  can you check this please. issue is there from quite sometime.
